export const PRIMARY_TEXT_COLOR = '#3A3B7B'
export const GRAY_COLOR = '#6F6D7B'
export const TEXTURE_PURPLE = '#7476ED'
export const LIGHT_PURPLE = '#E5E5E5'
export const MAGENTA = '#BF7EE6'
export const DARK_GRAY = '#312E43'
export const LIGHT_GRAY = '#6F6D7B'
export const ARROW_GRAY = '#9897A1'
